### ISSUE TITLE
More configurability request

### ISSUE THREAD

**Issue by msprev** [junegunn/vim-xmark#10]
vim-xmark is great, thank you! It would be even better if one could configure:

1. The options passed by vim-xmark to pandoc (e.g. the reader -- I want to write using pandoc flavour of markdown rather than github; I'd also like to select `--smart`)
2. Related to (1), the css file used by pandoc
3. A temporary directory for html files (I'd like to keep my temp html files in a single directory rather than littered around the filesystem).

Thank you for your great work!

**Comment by junegunn** [comment]
Yeah, it's a simple task of adding a few configuration variables, but I'm not going to make any major change to this project, so maybe it would be easier for you to just fork it and just change some bits as you like. What do you think? Regarding the point 3, the reason temp file is created in the same directory as the markdown file is to show images specified in relative paths.

**Comment by msprev** [comment]
Thanks. I'm happy to fork to do (1) and (2). I understand and agree with the reasoning for not doing (3). Thanks again for a great plugin.
