### ISSUE TITLE
Support for Google Chrome Canary

### ISSUE THREAD

**Issue by cooperuser** [junegunn/vim-xmark#12]
I use Google Chrome Canary as my main internet browser and it seems that this plugin only works for the default Chrome. Is there any way to easily detect which Chrome is being used on the system and use that application for the applescript?

**Comment by junegunn** [comment]
> Is there any way to easily detect which Chrome

I haven't tried but it's probably possible with Applescript. Or at least we should be able to find a running Chrome process. However we may find that neither of the versions is running at the point, or both versions are running. It's not clear what we should do then.

An easy way to support Canary is to make https://github.com/junegunn/vim-xmark/blob/7e27f6f/plugin/xmark.vim#L41 configurable.

**Comment by cooperuser** [comment]
I see. For now I will just change that value manually

**Comment by cooperuser** [comment]
I'm gonna go ahead and close this, as I am finally cleaning out my issues list.
