### ISSUE TITLE
vim-xmark can support preview-window auto-scroll up/down while editing markdown.

### ISSUE THREAD

**Issue by hawkinchina** [junegunn/vim-xmark#18]
vim-xmark can support preview-window auto-scroll up/down while editing markdown.
eg. when you edit the source markdown in the first line , and then you move the bottom of the file.
and edit again.  Can you let the preview window automatically scroll to the bottom while editing with two windows side by side.

**Comment by junegunn** [comment]
I don't use xmark anymore. Instead, I use https://github.com/iamcco/markdown-preview.nvim with https://github.com/junegunn/x5050

**Comment by hawkinchina** [comment]
I will try, thanks for your advice.
