### ISSUE TITLE
URI.escape is obsolete

### ISSUE THREAD

**Issue by nomasprime** [junegunn/vim-xmark#19]
Still works but throwing up this error:

```
Error detected while processing function <lambda>2[1]..<SNR>31_reload[19]..<SNR>31_urlencode:
line    4:
eval:2: warning: URI.escape is obsolete
```

**Comment by junegunn** [comment]
Hi, thanks for the report but I have to mention that I no longer use this plugin and thus stopped maintaining it. Instead, I use https://github.com/iamcco/markdown-preview.nvim along with https://github.com/junegunn/x5050.

**Comment by nomasprime** [comment]
Hi @junegunn. Thanks, I started using that too. Was unaware of x5050 though, I'll check it out.
