### ISSUE TITLE
Perform URL encoding properly

### ISSUE THREAD

**Issue by simnalamburt** [junegunn/vim-xmark#5]
Suppose that I performed `:Xmark` on a file whose path is `/Users/simnalamburt/Google Drive/README.md`. In Google Chrome, it'll be opened as `file:///Users/simnalamburt/Google%20Drive/.xmark.README.md.html`. With [current implementation][src], two URLs are considered different. Because of this, xmark opens a new tab everytime I save the file.

##### Reference
* [RFC 2396](https://www.ietf.org/rfc/rfc2396.txt)
* [RFC 3986](https://www.ietf.org/rfc/rfc3986.txt)

[src]: https://github.com/junegunn/vim-xmark/blob/8ac9368cd6a497bc12e2551aa96e71c01ee6524d/plugin/applescript/update.scpt#L12

**Comment by junegunn** [comment]
Continuing the discussion from #6:

> Yeah, I've given thought about the option as well. But the file name still can contain such characters, so we'll end up with something like /tmp/xmark-{pid}-{bufnr}.html. The downside of the scheme is that when you restart vim and restart xmark with the chrome tab open, we won't be able to reuse the tab.

I forgot to mention that the main reason I decided to place the temp file in the same directory as the markdown file was to correctly display images in the relative paths.

**Comment by simnalamburt** [comment]
Then performing urlencode sounds inevitable.

1. Implement urlencode in VimL somehow.
2. Try to call urlencode function of ruby, python2, python3.

Implementing urlencoding in VimL sounds so annoying for me, and most modern vim users compile vim with at least one of `+ruby`, `+python` and `+python3` enabled. Let's go with option 2.

**Comment by junegunn** [comment]
That sounds reasonable. With ruby, it's just a one-liner. I'll push a fix shortly.

**Comment by junegunn** [comment]
Seems to work fine. Thanks for the suggestion. It would be even nicer if we could also add `elseif has('python')` block :)

**Comment by simnalamburt** [comment]
Works perfect with Korean filepath! :+1:
